version: '2'
services:
  hadoop-slave1:
     image: hoult/docker-hive:2.3.7
     container_name: hadoop-slave1
     working_dir: /opt/hoult/servers
     hostname: linux122
     volumes:
       - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./docker-hive/conf:/usr/local/hive/conf
     networks:
       zoo:
         ipv4_address: 172.18.0.7
  hadoop-slave2:
     image: hoult/docker-hive:2.3.7
     container_name: hadoop-slave2
     working_dir: /opt/hoult/servers
     hostname: linux123
     volumes:
       - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./docker-hive/conf:/usr/local/hive/conf
     networks:
       zoo:
         ipv4_address: 172.18.0.8
  hadoop-master:
     image: hoult/docker-hive:2.3.7
     container_name: hadoop-master
     working_dir: /opt/hoult/servers
     hostname: linux121
     volumes:
       - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./docker-hive/conf:/usr/local/hive/conf
       - ~/DockData/hive/input:/input
     networks:
       zoo:
         ipv4_address: 172.18.0.9
     ports:
       - "50070:50070"
       - "9083:9083"
       - "8088:8088"
     links:
       - hadoop-slave1
       - hadoop-slave2

networks:
  zoo:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
