version: '2'

services:
  ch01:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9001:9000"
    volumes:
      - ./docker-clickhouse/ch01/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch01/data:/var/lib/clickhouse
    networks:
      zoo:
        ipv4_address: 172.19.0.11
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true

  ch02:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9002:9000"
    volumes:
      - ./docker-clickhouse/ch02/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch02/data:/var/lib/clickhouse
    networks:
      zoo:
        ipv4_address: 172.19.0.12
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true

  ch03:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9003:9000"
    volumes:
      - ./docker-clickhouse/ch03/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch03/data:/var/lib/clickhouse
    networks:
      zoo:
        ipv4_address: 172.19.0.13
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true

networks:
  zoo:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1