version: '2'

services:
  clickhouse01:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9001:9000"
    volumes:
      - ./docker-clickhouse/ch01/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch01/data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true

  clickhouse02:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9002:9000"
    volumes:
      - ./docker-clickhouse/ch02/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch02/data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true

  clickhouse03:
    image: yandex/clickhouse-server:1.1
    expose:
      - "9000"
    user: root
    ports:
      - "9003:9000"
    volumes:
      - ./docker-clickhouse/ch03/etc:/etc/clickhouse-server
      - ~/DockData/clickhouse/ch03/data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    privileged: true