version: '2.2'
services:
  es01:
    image: hoult/docker-elasticsearch:6.5.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/DockData/es-network/data01:/usr/share/elasticsearch/data
#      - ./docker-elasticsearch/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - es-network
  es02:
    image: hoult/docker-elasticsearch:6.5.4
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/DockData/es-network/data02:/usr/share/elasticsearch/data
#      - ./docker-elasticsearch/config/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es-network
  es03:
    image: hoult/docker-elasticsearch:6.5.4
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/DockData/es-network/data03:/usr/share/elasticsearch/data
#      - ./docker-elasticsearch/config/es03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es-network

networks:
  es-network:
    driver: bridge


## 单机模式
#  docker network create es-network
#  docker run -d --name elasticsearch --net es-network -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" hoult/docker-elasticsearch:6.5.4
#  启动kibana来管理
  ## `。查看ip  docker inspect elasticsearch | grep IPAddress
  docker run --name kibana -e ELASTICSEARCH_HOSTS=http://172.20.0.2:9200 --net es-network  -e SERVER_PORT=5601  -e SERVER_HOST=0.0.0.0 -p 5601:5601 -d kibana:6.5.4
