hadoop-slave1:
   image: hoult/docker-hive:1.2.2
   container_name: hadoop-slave1
   volumes:
     - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
     - ./docker-hive/conf:/usr/local/hive/conf
   net: zoo
hadoop-slave2:
   image: hoult/docker-hive:1.2.2
   container_name: hadoop-slave2
   volumes:
     - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
     - ./docker-hive/conf:/usr/local/hive/conf
   net: zoo
hadoop-master:
   image: hoult/docker-hive:1.2.2
   container_name: hadoop-master
   volumes:
     - ./docker-hadoop/conf:/usr/local/hadoop/etc/hadoop
     - ./docker-hive/conf:/usr/local/hive/conf
     - ~/DockData/hive/input:/input
   net: zoo
   ports:
     - "50070:50070"
     - "9083:9083"
     - "8088:8088"
   links:
     - hadoop-slave1
     - hadoop-slave2
