#  hoult/centos7:jdk8-ssh 版本逐渐commit而成
version: '2'
services:
  hadoop1:
     image: hoult/hadoop1
     working_dir: /opt/hoult/servers
     hostname: hadoop1
     container_name: hadoop1
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.21
  hadoop2:
     image: hoult/hadoop2
     hostname: hadoop2
     container_name: hadoop2
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.22
  hadoop3:
     image: hoult/hadoop3
     container_name: hadoop3
     hostname: hadoop3
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.23
  hadoop4:
     image: hoult/hadoop4
     container_name: hadoop4
     hostname: hadoop4
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.24
  hadoop5:
     image: hoult/hadoop5
     container_name: hadoop5
     hostname: hadoop5
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.25

networks:
  zoo:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
