kafka1:
  image: hoult/kafka
  restart: always
  container_name: kafka1
  net: zoo
  ports:
    - "9092:9092"
  environment:
    ZOO_MY_ID: 1
    ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888