#  hoult/centos7:jdk8-ssh 版本逐渐commit而成
version: '2'
services:
  hadoop1:
     image: hoult/hadoop1
     working_dir: /opt/hoult/servers
     hostname: hadoop1
     container_name: hadoop1
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.21
  hadoop2:
     image: hoult/hadoop2
     hostname: hadoop2
     container_name: hadoop2
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.22
  hadoop3:
     image: hoult/hadoop3
     container_name: hadoop3
     hostname: hadoop3
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.23
  hadoop4:
     image: hoult/hadoop4
     container_name: hadoop4
     hostname: hadoop4
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.24
  hadoop5:
     image: hoult/hadoop5
     container_name: hadoop5
     hostname: hadoop5
     privileged: true
     restart: always
     networks:
       zoo:
         ipv4_address: 172.19.0.25
  hadoop-mysql:
    #构建mysql镜像
    image: hoult/mysql:5.7
    container_name: hadoop-mysql # 容器名
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
      MYSQL_USER: bigdata   #创建bigdata用户
      MYSQL_PASSWORD: 123456  #设置bigdata用户的密码
    networks:
      zoo:
        ipv4_address: 172.19.0.5
    ports:
      - '8806:3306'  #host物理直接映射端口为8806
    privileged: true
    volumes:
      #mysql数据库挂载到host物理机目录
      - ~/DockData/mysql/data/db:/var/lib/mysql
      # 器的配置目录挂载到host物理机目录
      - ~/DockData/mysql/data/conf:/etc/mysql/conf.d
      #容器的日志目录挂载到host物理机日志目录
      - ~/DockData/mysql/logs:/logs
networks:
  zoo:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
